### ISSUE TITLE
API breakage in hmmlearn 0.2.7+

### ISSUE THREAD

**Issue by rekado** [BIMSBbioinfo/scregseg#8]
scregseg uses `hmmlearn._hmmc`, which in version 0.2.6 had `_forward` and `_backward` procedures.  As of hmmlearn 0.2.7 these procedures have been removed and replaced with `forward_scaling`, `forward_log`, `backward_scaling`, and `backward_log`.  These are not exactly drop in replacements as they have different call signatures.

**Comment by wkopp** [comment]
Hi Rekardo,
yes, that's right, thank you for pointing this out. They've replaced the cython backend in hmmlearn in hmmlearn 0.2.7.
My suggestion would be to define the hmmlearn dependence as 'hmmlearn<=0.2.6' in setup.py .
Would you have any objections to that? Otherwise, I'll do this in the next few days.
Best,
Wolfgang

**Comment by rekado** [comment]
Thanks for the quick reply!  Since hmmlearn 0.2.7 is now exactly one year old (and 0.2.8 has been released since) I think it would be good to adjust the caller instead.

**Comment by wkopp** [comment]
Thank you, I'll have a look at that.

**Comment by rekado** [comment]
Thanks!  This commit shows the API change most clearly: https://github.com/hmmlearn/hmmlearn/commit/61e3fd4da3c3c3fa927022da81364959f0bb3005
